language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

install:
  - pip install faker
  - ./build-package

script:
  - python -m unittest discover -s build/lib/py_obfuscate